# Generated by Django 5.2 on 2026-06-13 18:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('plantation_type', models.CharField(choices=[('FARM', 'Farm'), ('COMMUNITY', 'Community'), ('SCHOOL', 'School'), ('ROADSIDE', 'Roadside'), ('PARK', 'Park')], max_length=32)),
                ('location', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('target_trees', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('trees_planted', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='plantation_covers/')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='DRAFT', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.planterprofile')),
            ],
            options={
                'verbose_name': 'plantation project',
                'verbose_name_plural': 'plantation projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlantationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='project_updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='plantations.plantationproject')),
            ],
            options={
                'verbose_name': 'plantation update',
                'verbose_name_plural': 'plantation updates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=32)),
                ('tracking_number', models.CharField(blank=True, max_length=255)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('expected_delivery', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project support',
                'verbose_name_plural': 'project supports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('condition', models.CharField(choices=[('GOOD', 'Good'), ('ACCEPTABLE', 'Acceptable'), ('DAMAGED', 'Damaged')], max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('photo_proof', models.ImageField(blank=True, null=True, upload_to='confirmations/')),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('project_support', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation', to='plantations.projectsupport')),
            ],
            options={
                'verbose_name': 'receipt confirmation',
                'verbose_name_plural': 'receipt confirmations',
                'ordering': ['-confirmed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResourceNeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_needs', to='plantations.plantationproject')),
            ],
            options={
                'verbose_name': 'resource need',
                'verbose_name_plural': 'resource needs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectsupport',
            name='resource_need',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='plantations.resourceneed'),
        ),
        migrations.AddIndex(
            model_name='plantationproject',
            index=models.Index(fields=['plantation_type'], name='plantations_plantat_8bf4a9_idx'),
        ),
        migrations.AddIndex(
            model_name='plantationproject',
            index=models.Index(fields=['state'], name='plantations_state_a13cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='plantationproject',
            index=models.Index(fields=['status'], name='plantations_status_93550b_idx'),
        ),
    ]
